name: colored-mnist
channels: [pytorch, conda-forge, defaults]
dependencies:
  - python=3.10.13
  - pytorch
  - torchvision
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - ipywidgets
  - jupyter
  - ipykernel
  - pip
  - pip:
      - pyyaml
      - pillow
      - torchmetrics
      - tensorboard
      - nbdime
      - jupytext
      - nbstripout
      - umap-learn
      - grad-cam
      # Optional
      # - opencv-python-headless
      # - scikit-image
      # - albumentations
      # - captum
      # - wandb
